const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const sdl3_dep = b.dependency("sdl3", .{
        .target = target,
        .optimize = optimize,
    });

    const mod = b.createModule(.{
        .target = target,
        .optimize = optimize,
    });

    const lib = b.addLibrary(.{
        .name = "SDL3_ttf",
        .linkage = .static,
        .root_module = mod,
    });

    lib.version = std.SemanticVersion.parse("3.2.2") catch unreachable;

    lib.addIncludePath(b.path("include"));
    lib.addIncludePath(sdl3_dep.path("include"));
    lib.addIncludePath(sdl3_dep.path("include/build_config"));
    lib.addIncludePath(sdl3_dep.path("src"));
    lib.addIncludePath(b.path("external/plutovg/include"));
    lib.addIncludePath(b.path("external/plutosvg/source"));
    lib.addSystemIncludePath(.{ .cwd_relative = "/opt/homebrew/opt/freetype/include/freetype2" });

    mod.addCMacro("SDL_USE_BUILTIN_OPENGL_DEFINITIONS", "1");

    lib.addCSourceFiles(.{
        .root = b.path("src"),
        .files = &.{
            "SDL_hashtable.c",
            "SDL_hashtable_ttf.c",
            "SDL_gpu_textengine.c",
            "SDL_renderer_textengine.c",
            "SDL_surface_textengine.c",
            "SDL_ttf.c",
        },
        .flags = &.{
            "-DSDL_BUILD_MAJOR_VERSION=3",
            "-DSDL_BUILD_MINOR_VERSION=2",
            "-DSDL_BUILD_MICRO_VERSION=2",
            "-DBUILD_SDL",
        },
    });

    lib.addCSourceFiles(.{
        .root = b.path("external/plutovg"),
        .files = &.{
            "source/plutovg-ft-math.c",
            "source/plutovg-ft-raster.c",
            "source/plutovg-ft-stroker.c",
            "source/plutovg-blend.c",
            "source/plutovg-canvas.c",
            "source/plutovg-font.c",
            "source/plutovg-matrix.c",
            "source/plutovg-path.c",
            "source/plutovg-rasterize.c",
            "source/plutovg-surface.c",
            "source/plutovg-paint.c",
        },
    });

    lib.addCSourceFiles(.{
        .root = b.path("external/plutosvg"),
        .files = &.{"source/plutosvg.c"},
        .flags = &.{"-DPLUTOSVG_BUILD_STATIC"},
    });

    lib.addCSourceFiles(.{
        .root = sdl3_dep.path("src"),
        .files = &.{
            "SDL.c",
            "SDL_assert.c",
            "SDL_error.c",
            "SDL_guid.c",
            "SDL_hashtable.c",
            "SDL_hints.c",
            "SDL_list.c",
            "SDL_log.c",
            "SDL_properties.c",
            "SDL_utils.c",
            "atomic/SDL_atomic.c",
            "atomic/SDL_spinlock.c",
            "audio/SDL_audio.c",
            "audio/SDL_audiocvt.c",
            "audio/SDL_audiodev.c",
            "audio/SDL_audioqueue.c",
            "audio/SDL_audioresample.c",
            "audio/SDL_audiotypecvt.c",
            "audio/SDL_mixer.c",
            "audio/SDL_wave.c",
            "camera/SDL_camera.c",
            "cpuinfo/SDL_cpuinfo.c",
            "dialog/SDL_dialog.c",
            "dialog/SDL_dialog_utils.c",
            "dynapi/SDL_dynapi.c",
            "events/SDL_categories.c",
            "events/SDL_clipboardevents.c",
            "events/SDL_displayevents.c",
            "events/SDL_dropevents.c",
            "events/SDL_events.c",
            "events/SDL_eventwatch.c",
            "events/SDL_keyboard.c",
            "events/SDL_keymap.c",
            "events/SDL_keysym_to_keycode.c",
            "events/SDL_keysym_to_scancode.c",
            "events/SDL_mouse.c",
            "events/SDL_pen.c",
            "events/SDL_quit.c",
            "events/SDL_scancode_tables.c",
            "events/SDL_touch.c",
            "events/SDL_windowevents.c",
            "events/imKStoUCS.c",
            "filesystem/SDL_filesystem.c",
            "haptic/SDL_haptic.c",
            "hidapi/SDL_hidapi.c",
            "io/SDL_asyncio.c",
            "io/SDL_iostream.c",
            "joystick/SDL_gamepad.c",
            "joystick/SDL_joystick.c",
            "joystick/SDL_steam_virtual_gamepad.c",
            "joystick/controller_type.c",
            "stdlib/SDL_crc16.c",
            "stdlib/SDL_crc32.c",
            "stdlib/SDL_getenv.c",
            "stdlib/SDL_iconv.c",
            "stdlib/SDL_malloc.c",
            "stdlib/SDL_memcpy.c",
            "stdlib/SDL_memmove.c",
            "stdlib/SDL_memset.c",
            "stdlib/SDL_mslibc.c",
            "stdlib/SDL_murmur3.c",
            "stdlib/SDL_qsort.c",
            "stdlib/SDL_random.c",
            "stdlib/SDL_stdlib.c",
            "stdlib/SDL_string.c",
            "stdlib/SDL_strtokr.c",
            "storage/SDL_storage.c",
            "storage/generic/SDL_genericstorage.c",
            "test/SDL_test_assert.c",
            "test/SDL_test_common.c",
            "test/SDL_test_compare.c",
            "test/SDL_test_crc32.c",
            "test/SDL_test_font.c",
            "test/SDL_test_fuzzer.c",
            "test/SDL_test_harness.c",
            "test/SDL_test_log.c",
            "test/SDL_test_md5.c",
            "test/SDL_test_memory.c",
            "thread/SDL_thread.c",
            "timer/SDL_timer.c",
            "tray/SDL_tray_utils.c",
            "video/SDL_RLEaccel.c",
            "video/SDL_blit.c",
            "video/SDL_blit_0.c",
            "video/SDL_blit_1.c",
            "video/SDL_blit_A.c",
            "video/SDL_blit_N.c",
            "video/SDL_blit_auto.c",
            "video/SDL_blit_copy.c",
            "video/SDL_blit_slow.c",
            "video/SDL_bmp.c",
            "video/SDL_clipboard.c",
            "video/SDL_egl.c",
            "video/SDL_fillrect.c",
            "video/SDL_pixels.c",
            "video/SDL_rect.c",
            "video/SDL_rotate.c",
            "video/SDL_stb.c",
            "video/SDL_stretch.c",
            "video/SDL_surface.c",
            "video/SDL_video.c",
            "video/SDL_video_unsupported.c",
            "video/SDL_vulkan_utils.c",
            "video/SDL_yuv.c",
            "video/dummy/SDL_nullevents.c",
            "video/dummy/SDL_nullframebuffer.c",
            "video/dummy/SDL_nullvideo.c",
            "video/yuv2rgb/yuv_rgb_std.c",
            "video/yuv2rgb/yuv_rgb_sse.c",
            "video/yuv2rgb/yuv_rgb_lsx.c",
            "render/software/SDL_blendfillrect.c",
            "render/software/SDL_blendline.c",
            "render/software/SDL_blendpoint.c",
            "render/software/SDL_drawline.c",
            "render/software/SDL_drawpoint.c",
            "render/software/SDL_render_sw.c",
            "render/software/SDL_triangle.c",
            "audio/dummy/SDL_dummyaudio.c",
            "audio/disk/SDL_diskaudio.c",
            "joystick/hidapi/SDL_hidapi_8bitdo.c",
            "joystick/hidapi/SDL_hidapi_combined.c",
            "joystick/hidapi/SDL_hidapi_flydigi.c",
            "joystick/hidapi/SDL_hidapi_gamecube.c",
            "joystick/hidapi/SDL_hidapi_gip.c",
            "joystick/hidapi/SDL_hidapi_lg4ff.c",
            "joystick/hidapi/SDL_hidapi_luna.c",
            "joystick/hidapi/SDL_hidapi_ps3.c",
            "joystick/hidapi/SDL_hidapi_ps4.c",
            "joystick/hidapi/SDL_hidapi_ps5.c",
            "joystick/hidapi/SDL_hidapi_rumble.c",
            "joystick/hidapi/SDL_hidapi_shield.c",
            "joystick/hidapi/SDL_hidapi_sinput.c",
            "joystick/hidapi/SDL_hidapi_stadia.c",
            "joystick/hidapi/SDL_hidapi_steam.c",
            "joystick/hidapi/SDL_hidapi_steam_hori.c",
            "joystick/hidapi/SDL_hidapi_steam_triton.c",
            "joystick/hidapi/SDL_hidapi_steamdeck.c",
            "joystick/hidapi/SDL_hidapi_switch.c",
            "joystick/hidapi/SDL_hidapi_switch2.c",
            "joystick/hidapi/SDL_hidapi_wii.c",
            "joystick/hidapi/SDL_hidapi_xbox360.c",
            "joystick/hidapi/SDL_hidapi_xbox360w.c",
            "joystick/hidapi/SDL_hidapi_xboxone.c",
            "joystick/hidapi/SDL_hidapi_zuiki.c",
            "joystick/hidapi/SDL_hidapijoystick.c",
            "joystick/hidapi/SDL_report_descriptor.c",
            "joystick/virtual/SDL_virtualjoystick.c",
        },
    });

    lib.linkLibC();
    lib.linkSystemLibrary("freetype");
    lib.linkSystemLibrary("harfbuzz");

    const t = target.result;
    switch (t.os.tag) {
        .macos => {
            lib.addCSourceFiles(.{
                .root = sdl3_dep.path("src"),
                .files = &.{
                    "haptic/darwin/SDL_syshaptic.c",
                    "joystick/darwin/SDL_iokitjoystick.c",
                    "power/macos/SDL_syspower.c",
                    "timer/unix/SDL_systimer.c",
                    "loadso/dlopen/SDL_sysloadso.c",
                    "audio/disk/SDL_diskaudio.c",
                    "render/opengl/SDL_render_gl.c",
                    "render/opengl/SDL_shaders_gl.c",
                    "render/opengles2/SDL_render_gles2.c",
                    "render/opengles2/SDL_shaders_gles2.c",
                    "sensor/dummy/SDL_dummysensor.c",
                    "hidapi/mac/hid.c",
                    "thread/pthread/SDL_syscond.c",
                    "thread/pthread/SDL_sysmutex.c",
                    "thread/pthread/SDL_sysrwlock.c",
                    "thread/pthread/SDL_syssem.c",
                    "thread/pthread/SDL_systhread.c",
                    "thread/pthread/SDL_systls.c",
                },
            });
            lib.addCSourceFiles(.{
                .root = sdl3_dep.path("src"),
                .files = &.{
                    "audio/coreaudio/SDL_coreaudio.m",
                    "filesystem/cocoa/SDL_sysfilesystem.m",
                    "joystick/apple/SDL_mfijoystick.m",
                    "locale/macos/SDL_syslocale.m",
                    "misc/macos/SDL_sysurl.m",
                    "power/uikit/SDL_syspower.m",
                    "render/metal/SDL_render_metal.m",
                    "sensor/coremotion/SDL_coremotionsensor.m",
                    "video/cocoa/SDL_cocoaclipboard.m",
                    "video/cocoa/SDL_cocoaevents.m",
                    "video/cocoa/SDL_cocoakeyboard.m",
                    "video/cocoa/SDL_cocoamessagebox.m",
                    "video/cocoa/SDL_cocoametalview.m",
                    "video/cocoa/SDL_cocoamodes.m",
                    "video/cocoa/SDL_cocoamouse.m",
                    "video/cocoa/SDL_cocoaopengl.m",
                    "video/cocoa/SDL_cocoaopengles.m",
                    "video/cocoa/SDL_cocoapen.m",
                    "video/cocoa/SDL_cocoashape.m",
                    "video/cocoa/SDL_cocoavideo.m",
                    "video/cocoa/SDL_cocoavulkan.m",
                    "video/cocoa/SDL_cocoawindow.m",
                    "video/uikit/SDL_uikitappdelegate.m",
                    "video/uikit/SDL_uikitclipboard.m",
                    "video/uikit/SDL_uikitevents.m",
                    "video/uikit/SDL_uikitmessagebox.m",
                    "video/uikit/SDL_uikitmetalview.m",
                    "video/uikit/SDL_uikitmodes.m",
                    "video/uikit/SDL_uikitopengles.m",
                    "video/uikit/SDL_uikitopenglview.m",
                    "video/uikit/SDL_uikitpen.m",
                    "video/uikit/SDL_uikitvideo.m",
                    "video/uikit/SDL_uikitview.m",
                    "video/uikit/SDL_uikitviewcontroller.m",
                    "video/uikit/SDL_uikitvulkan.m",
                    "video/uikit/SDL_uikitwindow.m",
                    "tray/cocoa/SDL_tray.m",
                    "process/posix/SDL_posixprocess.c",
                    "core/unix/SDL_poll.c",
                    "core/unix/SDL_appid.c",
                    "core/unix/SDL_gtk.c",
                    "time/unix/SDL_systime.c",
                    "dialog/cocoa/SDL_cocoadialog.m",
                    "gpu/metal/SDL_gpu_metal.m",
                    "camera/coremedia/SDL_camera_coremedia.m",
                },
                .flags = &.{"-fobjc-arc"},
            });
            lib.linkFramework("GameController");
            lib.linkFramework("CoreHaptics");
            lib.linkFramework("OpenGL");
            lib.linkFramework("Metal");
            lib.linkFramework("CoreVideo");
            lib.linkFramework("Cocoa");
            lib.linkFramework("IOKit");
            lib.linkFramework("ForceFeedback");
            lib.linkFramework("Carbon");
            lib.linkFramework("CoreAudio");
            lib.linkFramework("AudioToolbox");
            lib.linkFramework("AVFoundation");
            lib.linkFramework("Foundation");
        },
        .linux => {
            lib.addCSourceFiles(.{
                .root = sdl3_dep.path("src"),
                .files = &.{
                    "core/linux/SDL_dbus.c",
                    "core/linux/SDL_evdev.c",
                    "core/linux/SDL_evdev_capabilities.c",
                    "core/linux/SDL_evdev_kbd.c",
                    "core/linux/SDL_fcitx.c",
                    "core/linux/SDL_ibus.c",
                    "core/linux/SDL_ime.c",
                    "core/linux/SDL_progressbar.c",
                    "core/linux/SDL_system_theme.c",
                    "core/linux/SDL_threadprio.c",
                    "core/linux/SDL_udev.c",
                    "core/unix/SDL_fribidi.c",
                    "core/unix/SDL_gtk.c",
                    "core/unix/SDL_libthai.c",
                    "core/unix/SDL_poll.c",
                    "haptic/linux/SDL_syshaptic.c",
                    "hidapi/linux/hid.c",
                    "power/linux/SDL_syspower.c",
                    "loadso/dlopen/SDL_sysloadso.c",
                    "audio/disk/SDL_diskaudio.c",
                    "audio/dummy/SDL_dummyaudio.c",
                    "timer/unix/SDL_systimer.c",
                    "thread/pthread/SDL_syscond.c",
                    "thread/pthread/SDL_sysmutex.c",
                    "thread/pthread/SDL_sysrwlock.c",
                    "thread/pthread/SDL_syssem.c",
                    "thread/pthread/SDL_systhread.c",
                    "thread/pthread/SDL_systls.c",
                    "thread/generic/SDL_sysmutex.c",
                    "thread/generic/SDL_sysrwlock.c",
                    "thread/generic/SDL_syssem.c",
                    "thread/generic/SDL_systhread.c",
                    "thread/generic/SDL_systls.c",
                    "filesystem/unix/SDL_sysfilesystem.c",
                    "filesystem/posix/SDL_sysfsops.c",
                    "locale/unix/SDL_syslocale.c",
                    "misc/unix/SDL_sysurl.c",
                    "sensor/dummy/SDL_dummysensor.c",
                    "process/posix/SDL_posixprocess.c",
                    "time/unix/SDL_systime.c",
                    "tray/unix/SDL_tray.c",
                    "joystick/linux/SDL_sysjoystick.c",
                    "joystick/hidapi/SDL_hidapi_8bitdo.c",
                    "joystick/hidapi/SDL_hidapi_combined.c",
                    "joystick/hidapi/SDL_hidapi_gamecube.c",
                    "joystick/hidapi/SDL_hidapi_gip.c",
                    "joystick/hidapi/SDL_hidapi_lg4ff.c",
                    "joystick/hidapi/SDL_hidapi_ps4.c",
                    "joystick/hidapi/SDL_hidapi_ps5.c",
                    "joystick/hidapi/SDL_hidapi_rumble.c",
                    "joystick/hidapi/SDL_hidapi_shield.c",
                    "joystick/hidapi/SDL_hidapi_steam.c",
                    "joystick/hidapi/SDL_hidapi_steamdeck.c",
                    "joystick/hidapi/SDL_hidapi_switch.c",
                    "joystick/hidapi/SDL_hidapi_switch2.c",
                    "joystick/hidapi/SDL_hidapi_xbox360.c",
                    "joystick/hidapi/SDL_hidapi_xboxone.c",
                    "joystick/hidapi/SDL_hidapijoystick.c",
                    "joystick/virtual/SDL_virtualjoystick.c",
                    "haptic/hidapi/SDL_hidapihaptic.c",
                    "haptic/hidapi/SDL_hidapihaptic_lg4ff.c",
                },
            });
            lib.addCSourceFiles(.{
                .root = sdl3_dep.path("src"),
                .files = &.{
                    "video/x11/SDL_x11clipboard.c",
                    "video/x11/SDL_x11dyn.c",
                    "video/x11/SDL_x11events.c",
                    "video/x11/SDL_x11framebuffer.c",
                    "video/x11/SDL_x11keyboard.c",
                    "video/x11/SDL_x11messagebox.c",
                    "video/x11/SDL_x11modes.c",
                    "video/x11/SDL_x11mouse.c",
                    "video/x11/SDL_x11opengl.c",
                    "video/x11/SDL_x11opengles.c",
                    "video/x11/SDL_x11pen.c",
                    "video/x11/SDL_x11settings.c",
                    "video/x11/SDL_x11shape.c",
                    "video/x11/SDL_x11toolkit.c",
                    "video/x11/SDL_x11touch.c",
                    "video/x11/SDL_x11video.c",
                    "video/x11/SDL_x11vulkan.c",
                    "video/x11/SDL_x11window.c",
                    "video/x11/SDL_x11xfixes.c",
                    "video/x11/SDL_x11xinput2.c",
                    "video/x11/SDL_x11xsync.c",
                    "video/x11/SDL_x11xtest.c",
                    "video/x11/edid-parse.c",
                    "video/x11/xsettings-client.c",
                    "video/wayland/SDL_waylandclipboard.c",
                    "video/wayland/SDL_waylandcolor.c",
                    "video/wayland/SDL_waylanddatamanager.c",
                    "video/wayland/SDL_waylanddyn.c",
                    "video/wayland/SDL_waylandevents.c",
                    "video/wayland/SDL_waylandkeyboard.c",
                    "video/wayland/SDL_waylandmessagebox.c",
                    "video/wayland/SDL_waylandmouse.c",
                    "video/wayland/SDL_waylandopengles.c",
                    "video/wayland/SDL_waylandshmbuffer.c",
                    "video/wayland/SDL_waylandvideo.c",
                    "video/wayland/SDL_waylandvulkan.c",
                    "video/wayland/SDL_waylandwindow.c",
                    "audio/alsa/SDL_alsa_audio.c",
                    "audio/pulseaudio/SDL_pulseaudio.c",
                    "audio/jack/SDL_jackaudio.c",
                    "audio/pipewire/SDL_pipewire.c",
                    "dialog/unix/SDL_portaldialog.c",
                    "dialog/unix/SDL_unixdialog.c",
                    "dialog/unix/SDL_zenitydialog.c",
                    "dialog/unix/SDL_zenitymessagebox.c",
                },
            });
            lib.linkSystemLibrary("dbus");
            lib.linkSystemLibrary("udev");
        },
        .windows => {
            lib.addCSourceFiles(.{
                .root = sdl3_dep.path("src"),
                .files = &.{
                    "core/windows/SDL_hid.c",
                    "core/windows/SDL_immdevice.c",
                    "core/windows/SDL_windows.c",
                    "core/windows/SDL_xinput.c",
                    "core/windows/pch.c",
                    "filesystem/windows/SDL_sysfilesystem.c",
                    "filesystem/windows/SDL_sysfsops.c",
                    "haptic/windows/SDL_dinputhaptic.c",
                    "haptic/windows/SDL_windowshaptic.c",
                    "haptic/windows/SDL_xinputhaptic.c",
                    "hidapi/windows/hid.c",
                    "hidapi/windows/hidapi_descriptor_reconstruct.c",
                    "joystick/windows/SDL_dinputjoystick.c",
                    "joystick/windows/SDL_rawinputjoystick.c",
                    "joystick/windows/SDL_windows_gaming_input.c",
                    "joystick/windows/SDL_windowsjoystick.c",
                    "joystick/windows/SDL_xinputjoystick.c",
                    "loadso/windows/SDL_sysloadso.c",
                    "locale/windows/SDL_syslocale.c",
                    "misc/windows/SDL_sysurl.c",
                    "power/windows/SDL_syspower.c",
                    "sensor/windows/SDL_windowssensor.c",
                    "timer/windows/SDL_systimer.c",
                    "video/windows/SDL_windowsclipboard.c",
                    "video/windows/SDL_windowsevents.c",
                    "video/windows/SDL_windowsframebuffer.c",
                    "video/windows/SDL_windowskeyboard.c",
                    "video/windows/SDL_windowsmessagebox.c",
                    "video/windows/SDL_windowsmodes.c",
                    "video/windows/SDL_windowsmouse.c",
                    "video/windows/SDL_windowsopengl.c",
                    "video/windows/SDL_windowsopengles.c",
                    "video/windows/SDL_windowsrawinput.c",
                    "video/windows/SDL_windowsshape.c",
                    "video/windows/SDL_windowsvideo.c",
                    "video/windows/SDL_windowsvulkan.c",
                    "video/windows/SDL_windowswindow.c",
                    "thread/windows/SDL_syscond_cv.c",
                    "thread/windows/SDL_sysmutex.c",
                    "thread/windows/SDL_sysrwlock_srw.c",
                    "thread/windows/SDL_syssem.c",
                    "thread/windows/SDL_systhread.c",
                    "thread/windows/SDL_systls.c",
                    "thread/generic/SDL_sysmutex.c",
                    "thread/generic/SDL_sysrwlock.c",
                    "thread/generic/SDL_syssem.c",
                    "thread/generic/SDL_systhread.c",
                    "thread/generic/SDL_systls.c",
                    "render/direct3d/SDL_render_d3d.c",
                    "render/direct3d/SDL_shaders_d3d.c",
                    "render/direct3d11/SDL_render_d3d11.c",
                    "render/direct3d11/SDL_shaders_d3d11.c",
                    "render/direct3d12/SDL_render_d3d12.c",
                    "render/direct3d12/SDL_shaders_d3d12.c",
                    "audio/directsound/SDL_directsound.c",
                    "audio/wasapi/SDL_wasapi.c",
                    "audio/wasapi/SDL_wasapi_win32.c",
                    "audio/winmm/SDL_winmm.c",
                    "audio/disk/SDL_diskaudio.c",
                    "audio/dummy/SDL_dummyaudio.c",
                    "process/windows/SDL_windowsprocess.c",
                    "time/windows/SDL_systime.c",
                    "tray/windows/SDL_tray.c",
                },
            });
            lib.linkSystemLibrary("setupapi");
            lib.linkSystemLibrary("winmm");
            lib.linkSystemLibrary("gdi32");
            lib.linkSystemLibrary("imm32");
            lib.linkSystemLibrary("version");
            lib.linkSystemLibrary("oleaut32");
            lib.linkSystemLibrary("ole32");
        },
        else => {},
    }

    b.installArtifact(lib);
}
